CadeMeuMedico/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CadeMeuMedico.Models;
using System.Data.Entity;

namespace CadeMeuMedico.Controllers
{
    public class MedicosController : BaseController
    {
		private CadeMeuMedicoBDEntities db = new CadeMeuMedicoBDEntities();
        // GET: Medicos
        public ActionResult Index()
        {
			var medicos = db.Medico.Include(m => m.Cidade)
				.Include(m => m.Especialidade).ToList();
            return View(medicos);
        }

		public ActionResult Adicionar()
		{
			ViewBag.IDCidade = new SelectList(db.Cidade, "IDCidade", "Nome");
			ViewBag.IDEspecialidade = new SelectList(db.Especialidade, "IDEspecialidade", "Nome");
			return View();
		}

		[HttpPost]
		public ActionResult Adicionar(Medico medico)
		{
			if (ModelState.IsValid)
			{
				db.Medico.Add(medico);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			ViewBag.IDCidade = new SelectList(db.Cidade, "IDCidade", "Nome");
			ViewBag.IDEspecialidade = new SelectList(db.Especialidade, "IDEspecialidade", "Nome");
			return View(medico);
		}

		public ActionResult Editar(long id)
		{
			Medico medico = db.Medico.Find(id);
			ViewBag.IDCidade = new SelectList(db.Cidade, "IDCidade", "Nome");
			ViewBag.IDEspecialidade = new SelectList(db.Especialidade, "IDEspecialidade", "Nome");
			return View(medico);
		}

		[HttpPost]
		public ActionResult Editar(Medico medico)
		{
			if (ModelState.IsValid)
			{
				db.Entry(medico).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			ViewBag.IDCidade = new SelectList(db.Cidade, "IDCidade", "Nome");
			ViewBag.IDEspecialidade = new SelectList(db.Especialidade, "IDEspecialidade", "Nome");
			return View(medico);
		}

		public ActionResult Deletar(long id)
		{
			Medico medico = db.Medico.Find(id);
			ViewBag.IDCidade = new SelectList(db.Cidade, "Cidade", "Nome");
			ViewBag.IDEspecialidade = new SelectList(db.Especialidade, "Especialide", "Nome");
			return View(medico);
		}

		[HttpPost]
		public string Deletar(Medico medico)
		{
			try
			{
				//Medico medico = db.Medico.Find(id);
				db.Medico.Remove(medico);
				db.SaveChanges();
				return Boolean.TrueString;

			}
			catch
			{
				return Boolean.FalseString;
			}
		}
	}
}

CadeMeuMedico/Views/Layout.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Cade meu medico? - @ViewBag.Title</title>
	<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
	<style>
		body {
			padding-top: 60px;
		}
	</style>

</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header"> <a class="navbar-brand" href="#">Cade meu medico?</a> </div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#">Home</a></li>
					<li id="menuMedicos">
						@Html.ActionLink("Médicos", "Index", "Medicos")
					</li>
					<li id="menuEspecialidades">
						@Html.ActionLink("Especialidades", "Index", "Especialidades")
					</li>
					<li id="menuCidades">
						@Html.ActionLink("Cidades", "Index", "Cidades")
					</li>
					<li id="menuPaises">
						@Html.ActionLink("Países", "Index", "Paises")
					</li>
					<li>@TwitterGoodies.FollowButton("yoshidf", TwitterGoodies.FollowStyles.LogoSmall, TwitterGoodies.FollowColors.Blue)</li>
					<li>@TwitterGoodies.TweetButton(TwitterGoodies.DataCount.Horizontal, 
					   "Tweet","www.cademeumedico.com", TwitterGoodies.Languages.English, "yoshidf")</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container">
		@RenderBody()
	</div>

	<script src="@Url.Content("~/Scripts/jquery-3.1.0.min.js")"></script>
	<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>

	@RenderSection("scripts", required: false)
</body>
</html>